### ISSUE TITLE
Erro main

### ISSUE THREAD

**Issue by joaomas** [monanadmin/scripts_CD-CT#3]
@deniseiras e @carlosrenatosouza2 a 'main' do CD-CT esta com bug, estou usando a 'develop'.

$ ./1.install_monan.bash https://github.com/joaomas/MONAN-Model-JMAS.git

==> Moduling environment for MONAN model...

Currently Loaded Modules:
  1) autotools    4) ohpc                   7) mpich-4.0.2-gcc-9.4.0-gpof2pv  10) cdo-2.0.4-gcc-9.4.0-bjulvnd
  2) prun/2.2     5) netcdf/4.7.4           8) hwloc/2.5.0                    11) opengrads-2.2.1
  3) gnu9/9.4.0   6) netcdf-fortran/4.5.3   9) phdf5/1.10.8                   12) metis/5.1.0

 

==> Cloning your fork repository...

fatal: could not create work tree dir '/mnt/beegfs/carlos.souza/repo_Monan/scripts_CD-CT/sources/MONAN-Model_v0.1.0': Permission denied
==> An error occurred while cloning your fork. Possible causes:  wrong URL, user or password.

**Comment by deniseiras** [comment]
Isso, use a develop, ela está com as ultimas alterações

Em sex., 26 de abr. de 2024 17:39, João Messias ***@***.***>
escreveu:

**Comment by joaomas** [comment]
Corrigido na nova versão 0.1.0.
